[package]
name = "nautilus-dydx"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "dYdX v4 exchange integration adapter for the Nautilus trading engine"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false # Do not publish to crates.io for now

[lints]
workspace = true

[lib]
name = "nautilus_dydx"
crate-type = ["rlib", "cdylib"]

[features]
default = ["high-precision"]
extension-module = [
  "nautilus-common/extension-module",
  "nautilus-core/extension-module",
  "nautilus-data/extension-module",
  "nautilus-model/extension-module",
  "nautilus-network/extension-module",
  "python",
  "pyo3/extension-module",
]
python = [
  "nautilus-common/python",
  "nautilus-core/python",
  "nautilus-data/python",
  "nautilus-model/python",
  "nautilus-network/python",
  "pyo3",
  "pyo3-async-runtimes",
]
high-precision = ["nautilus-model/high-precision"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nautilus-common = { workspace = true, features = ["live"] }
nautilus-core = { workspace = true }
nautilus-data = { workspace = true }
nautilus-execution = { workspace = true }
nautilus-live = { workspace = true }
nautilus-model = { workspace = true }
nautilus-network = { workspace = true }
nautilus-system = { workspace = true }

ahash = { workspace = true }
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
bip32 = { workspace = true }
chrono = { workspace = true }
cosmrs = { workspace = true }
dashmap = { workspace = true }
derive_builder = { workspace = true }
dydx-proto = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
rust_decimal = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true } # Needed for bin scripts
urlencoding = { workspace = true }
ustr = { workspace = true }

pyo3 = { workspace = true, optional = true }
pyo3-async-runtimes = { workspace = true, optional = true }

[dev-dependencies]
nautilus-testkit = { workspace = true }
axum = { workspace = true }
criterion = { workspace = true }
rstest = { workspace = true }
rust_decimal_macros = { workspace = true }
tracing-test = { workspace = true }
url = { workspace = true }
indexmap = { workspace = true }

[[bin]]
name = "dydx-http-public"
path = "bin/http_public.rs"
doc = false

[[bin]]
name = "dydx-http-private"
path = "bin/http_private.rs"
doc = false

[[bin]]
name = "dydx-ws-data"
path = "bin/ws_data.rs"
doc = false

[[bin]]
name = "dydx-live-integration"
path = "bin/live_integration.rs"
doc = false

[[bin]]
name = "dydx-grpc-exec"
path = "bin/grpc_exec.rs"
doc = false

[[bin]]
name = "dydx-ws-exec"
path = "bin/ws_exec.rs"
doc = false
